# Rift main configuration

teleport-delay:
  enabled: true
  seconds: 5
  particle: HAPPY_VILLAGER
  particle-radius: 1
  particle-count: 10
  sound: ENTITY_ENDERMAN_TELEPORT
  sound-volume: 1
  sound-pitch: 1

teleport-complete:
  sound: ENTITY_ENDERMAN_TELEPORT
  sound-volume: 1
  sound-pitch: 1
  particle: FLAME
  particle-radius: 1
  particle-count: 10

warp-name:
  min-length: 3
  max-length: 16

